name: Daily Email Reminder

on:
  schedule:
    - cron: '26 2 * * *'
  workflow_dispatch:

env:
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  FROM: ${{ secrets.FROM }}
  TO: ${{ secrets.TO }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: npm ci

      - run: node src/main.js
